CREATE TABLE TB_USER (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    dieta ENUM('VEGETARIANA','VEGANA','ONIVORA','CARNIVORA','LOW_CARB') NOT NULL
);

CREATE TABLE TB_FOOD_ITEM (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    categoria ENUM('FRUTA','VERDURA','CARNES','LATICINIOS','OUTROS') NOT NULL,
    quantidade INT NOT NULL,
    validade DATE NOT NULL,
    user_id BIGINT,
    CONSTRAINT fk_tb_food_user FOREIGN KEY (user_id) REFERENCES TB_USER(id) ON DELETE CASCADE
);
